SELECT a.HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM (
    SELECT ANIMAL_ID, HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
) AS a
INNER JOIN ANIMAL_OUTS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.HOUR BETWEEN 9 AND 19
GROUP BY a.HOUR
ORDER BY a.HOUR;